cmake_minimum_required(VERSION 3.10)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

project(MyProject LANGUAGES C CXX)

function(print)
    foreach(var ${ARGN})
        message("${var} = ${${var}}")
    endforeach(var ${ARGN})
endfunction()

# Find Doxygen package
find_package(Doxygen QUIET)
find_package(libcmaes REQUIRED)
find_package(marty REQUIRED)
# Define a cache variable for enabling/disabling documentation
option(BUILD_DOCUMENTATION "Generate documentation with Doxygen" ${DOXYGEN_FOUND})

# Defining which models are to be compiled
# Define MODELS_LIBS_NAMES as a cache variable with an empty default value
set(MODELS_LIBS_NAMES "" CACHE STRING "List of model libraries to compile")

# Define a cache variable for enabling/disabling the submodule compilation
option(ENABLE_SUBMODULE_CMA "Enable compilation of the submodule CMA and dependent libraries" OFF)

# Function to list all models
function(list_all_models RESULT_VAR)
    set(LOCAL_MODELS_LIBS_NAMES "")
    
    # Get all directories in src/ starting with dp_
    file(GLOB DP_LIBRARIES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "src/dp_*")

    # Loop through each library path and extract the name
    foreach(lib_path ${DP_LIBRARIES})
        # Extract the library name by removing "src/" prefix
        string(REGEX REPLACE "^src/" "" lib_name ${lib_path})
        list(APPEND LOCAL_MODELS_LIBS_NAMES ${lib_name})
    endforeach()

    # Set the result variable in the parent scope
    set(${RESULT_VAR} ${LOCAL_MODELS_LIBS_NAMES} PARENT_SCOPE)
endfunction()

if(NOT MODELS_LIBS_NAMES)
    list_all_models(MODELS_LIBS_NAMES)
endif()
print(MODELS_LIBS_NAMES)

# List of the names of the libraries auto-generated by MARTY
set(PLAIN_MODELS_LIBS_NAMES "")
foreach(lib ${MODELS_LIBS_NAMES})
    string(REGEX REPLACE "^dp_" "" plain_lib ${lib})
    list(APPEND PLAIN_MODELS_LIBS_NAMES ${plain_lib})
endforeach()
print(PLAIN_MODELS_LIBS_NAMES)

# Options to be applied to ALL the projects
    # Set C++ standard globally
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)

    # Set C standard globally
    set(CMAKE_C_STANDARD 17)
    set(CMAKE_C_STANDARD_REQUIRED ON)

    # Set global compilation flags (applied to all targets)
    set(GENERIC_FLAGS "-Wall -Wextra -Wpedantic -Wno-deprecated-declarations -fPIC -fdiagnostics-color=always")
    set(MATH_OPTI_FLAGS "-fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${GENERIC_FLAGS} ${MATH_OPTI_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GENERIC_FLAGS} ${MATH_OPTI_FLAGS} -Wshadow")

    # Debug mode flags (applied when building with Debug configuration)
    set(DEBUG_FLAGS "-g -O0") # Enable debug symbols, disable optimization
    set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${DEBUG_FLAGS}")
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${DEBUG_FLAGS}")

    # Release mode flags (applied when building with Release configuration)
    set(RELEASE_FLAGS "-O3 -DNDEBUG") # Optimize for performance, disable debugging features
    set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ${RELEASE_FLAGS}")
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${RELEASE_FLAGS}")

    # Adding pthread to the external libs, to enable multithreading 
    set(EXTERNAL_LIBS pthread)

# Add subdirectories (add subprojects here, like your libraries and tests)
add_subdirectory(src/DPMathLib)

# Options to be applied to the dp_ libraries and the executables
    # Define the list of external libraries: 
    # Appending looptools, the fortran library, GSL, and MARTY
    set(EXTERNAL_LIBS ${EXTERNAL_LIBS} 
        ooptools 
        gfortran 
        gsl 
        gslcblas
        marty-lha
    )
    # Define the list of compile options (if needed)
    set(COMPILE_LINK_FLAGS
        -lpthread
        -looptools
        -lgfortran
        -lgsl
        -lgslcblas
        -lmarty-lha
    )

# Initiating the variable that contains all the libraries whose headers need to be installed before build
set(LISTS_COMMANDS_TO_INSTALL_HEADERS_ONLY DPMathLib)

foreach(dplib IN LISTS MODELS_LIBS_NAMES)
    # Adding the models to the projects
    add_subdirectory(src/${dplib}) 
    # Adding the command to install the header of the model to the dependencies of the global command defined next
    list(APPEND LISTS_COMMANDS_TO_INSTALL_HEADERS_ONLY install_headers_${dplib}) 
endforeach()

# Create a custom target for headers installation
add_custom_target(install_headers_all ALL DEPENDS ${LISTS_COMMANDS_TO_INSTALL_HEADERS_ONLY})

add_subdirectory(src/Test)

# Options to be applied to the dp_ libraries and the executables
# Appending CMA-ES to the list of external libs to be linked 
if(ENABLE_SUBMODULE_CMA)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/submodules/CMA-ES/CMakeLists.txt")
        # This submodule contains the CMA-ES algorithms for the parameter
        # space sampling
        add_subdirectory(submodules/CMA-ES)
        set(EXTERNAL_LIBS ${EXTERNAL_LIBS} cmaes)
        add_subdirectory(src/main)
        message(STATUS "CMA submodule and dependent libraries are now enabled for compilation")
    else()
        message(WARNING "CMA submodule directory not found. Please initialize and update the submodule.")
        set(ENABLE_SUBMODULE_CMA OFF CACHE BOOL "Enable compilation of the CMA submodule and dependent libraries" FORCE)
    endif()
else()
    message(STATUS "Submodule and dependent libraries disabled")
endif()

if(BUILD_DOCUMENTATION)
    if(DOXYGEN_FOUND)
        # Set input and output files
        set(DOXYGEN_IN ${CMAKE_CURRENT_SOURCE_DIR}/doc/Doxyfile)
        set(DOXYGEN_OUT ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile)

        # Request to configure the file
        configure_file(${DOXYGEN_IN} ${DOXYGEN_OUT} @ONLY)

        # Add a custom target for documentation generation
        add_custom_target(darkpack_doc
            COMMAND ${DOXYGEN_EXECUTABLE} ${DOXYGEN_OUT}
            WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
            COMMENT "Generating HTML and LaTex documentation with Doxygen"
            VERBATIM
        )
        message(STATUS "Doxygen found. Documentation will be generated.")
    else()
        message(WARNING "Doxygen not found. Documentation will not be generated.")
        set(BUILD_DOCUMENTATION OFF CACHE BOOL "Generate documentation with Doxygen" FORCE)
    endif()
else()
    message(STATUS "Documentation generation is disabled.")
endif()


# Add a custom target to run clang-format on all source files
find_program(CLANG_FORMAT_BIN clang-format)
## Define a cache variable for enabling/disabling clang-format to modify files
option(ENABLE_CLANG_FORMAT "Enable clang-format run" ON)

## Define the patterns to exclude
### Adding general patterns
set(EXCLUDE_PATTERNS
    "/submodules/"
    "/build/"
    "/src/.*/initialise_map.*"
    "/src/dp_.*/config.hpp"
    # Add more patterns as needed
)

### Adding all the libraries auto-generated by MARTY
#### List of the paths of ALL the libraries auto-generated by MARTY
list_all_models(ALL_MODELS_LIBS_NAMES)
set(PLAIN_MODELS_LIBS_PATHS "")
foreach(lib ${ALL_MODELS_LIBS_NAMES})
    string(REGEX REPLACE "^dp_" "/src/" plain_lib ${lib})
    list(APPEND PLAIN_MODELS_LIBS_PATHS ${plain_lib})
endforeach()
#### Appending to the list and printing
list(APPEND EXCLUDE_PATTERNS ${PLAIN_MODELS_LIBS_PATHS})
print(EXCLUDE_PATTERNS)

## Function to check if a file should be excluded
function(should_exclude FILE_PATH)
    foreach(PATTERN ${EXCLUDE_PATTERNS})
        if(${FILE_PATH} MATCHES ${PATTERN})
            set(SHOULD_EXCLUDE TRUE PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(SHOULD_EXCLUDE FALSE PARENT_SCOPE)
endfunction()

# Collect all source files
file(GLOB_RECURSE ALL_SOURCE_FILES 
    ${CMAKE_SOURCE_DIR}/src/*.cpp
    ${CMAKE_SOURCE_DIR}/src/*.hpp
    ${CMAKE_SOURCE_DIR}/include/*.hpp
)

## Filter out excluded files
set(FILTERED_SOURCE_FILES "")
foreach(SOURCE_FILE ${ALL_SOURCE_FILES})
    should_exclude(${SOURCE_FILE})
    if(NOT SHOULD_EXCLUDE)
        list(APPEND FILTERED_SOURCE_FILES ${SOURCE_FILE})
    endif()
endforeach()

if(ENABLE_CLANG_FORMAT)
    ## Create the format target
    add_custom_target(format
        COMMENT "Running clang-format to change files"
        COMMAND ${CLANG_FORMAT_BIN}
        -style=file
        -i
        ${FILTERED_SOURCE_FILES}
    )
endif()

## Create the format-check target
add_custom_target(format-check
    COMMENT "Running clang-format to check code style compliance"
    COMMAND ${CLANG_FORMAT_BIN}
    -style=file
    --dry-run
    --Werror
    ${FILTERED_SOURCE_FILES}
)