#include "correspondance.hpp"
namespace su2f2to2::corr{
const std::unordered_map<std::string, Entry_t> squaredampl{ 
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::V_3,EMPTYCHAR+corr::V_3},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_V_3_V_3, 8,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::V_3,EMPTYCHAR+corr::phi},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_V_3_phi, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::V,EMPTYCHAR+corr::V},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_V_V, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_e},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_nu_e_nu_e, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_mu},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_nu_e_nu_mu, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_nu_e_nu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::nu_mu,EMPTYCHAR+corr::nu_mu},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_nu_mu_nu_mu, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::nu_mu,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_nu_mu_nu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::nu_tau,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_nu_tau_nu_tau, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::e},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_e_e, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::mu},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_e_mu, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_e_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::mu,EMPTYCHAR+corr::mu},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_mu_mu, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::mu,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_mu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_1,ANTICHAR,EMPTYCHAR+corr::tau,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_1_to_anti_tau_tau, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::V,EMPTYCHAR+corr::phi},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_V_phi, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_e},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_nu_e_nu_e, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_mu},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_nu_e_nu_mu, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_nu_e_nu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_mu,EMPTYCHAR+corr::nu_mu},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_nu_mu_nu_mu, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_mu,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_nu_mu_nu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_tau,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_nu_tau_nu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::e},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_e_e, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::mu},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_e_mu, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_e_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::mu,EMPTYCHAR+corr::mu},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_mu_mu, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::mu,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_mu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_1,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::tau,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_1_chi_dm_2_to_anti_tau_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::V_3,EMPTYCHAR+corr::V_3},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_V_3_V_3, 8,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::V_3,EMPTYCHAR+corr::phi},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_V_3_phi, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::V,EMPTYCHAR+corr::V},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_V_V, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_e},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_nu_e_nu_e, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_mu},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_nu_e_nu_mu, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_e,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_nu_e_nu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_mu,EMPTYCHAR+corr::nu_mu},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_nu_mu_nu_mu, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_mu,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_nu_mu_nu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::nu_tau,EMPTYCHAR+corr::nu_tau},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_nu_tau_nu_tau, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::e},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_e_e, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::mu},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_e_mu, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::e,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_e_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::mu,EMPTYCHAR+corr::mu},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_mu_mu, 4,1} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::mu,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_mu_tau, 4,2} },
{ {ANTICHAR,EMPTYCHAR+corr::chi_dm_2,EMPTYCHAR+corr::chi_dm_2,ANTICHAR,EMPTYCHAR+corr::tau,EMPTYCHAR+corr::tau},{  &c_sumSqAmpl_anti_chi_dm_2_chi_dm_2_to_anti_tau_tau, 4,1} },
};
}
