#include "group_g.h"
namespace u1f2to2 {

const std::array<Callable<complex_t, param_t>, 38> f_G = {
    Callable{"m_chi_dm_1", m_chi_dm_1},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_V_3", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_V_3},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_anti_V_3", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_anti_V_3},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_phi", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_phi},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_anti_phi", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_anti_phi},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_V_3", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_V_3},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_anti_V_3", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_anti_V_3},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_phi", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_phi},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_anti_phi", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_anti_phi},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_e", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_e},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_mu", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_mu},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_e", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_e},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_mu", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_mu},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_mu_anti_nu_mu", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_mu_anti_nu_mu},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_mu_anti_nu_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_mu_anti_nu_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_mu_nu_mu", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_mu_nu_mu},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_mu_nu_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_mu_nu_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_tau_anti_nu_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_tau_anti_nu_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_tau_nu_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_tau_nu_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_e", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_e},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_mu", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_mu},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_e", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_e},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_mu", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_mu},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_mu_anti_mu", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_mu_anti_mu},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_mu_anti_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_mu_anti_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_mu_mu", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_mu_mu},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_mu_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_mu_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_tau_anti_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_tau_anti_tau},
    Callable{"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_tau_tau", sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_tau_tau},
    Callable{"width_h", width_h},
    Callable{"width_W", width_W},
    Callable{"width_Z", width_Z},
    Callable{"width_t", width_t},
    Callable{"width_V_3", width_V_3},
};

const std::map<std::string, Callable<complex_t, param_t>> fmap_G {
    {"m_chi_dm_1", f_G[0]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_V_3", f_G[1]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_anti_V_3", f_G[2]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_phi", f_G[3]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_V_3_anti_phi", f_G[4]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_V_3", f_G[5]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_anti_V_3", f_G[6]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_phi", f_G[7]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_V_3_anti_phi", f_G[8]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_e", f_G[9]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_mu", f_G[10]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_e_anti_nu_tau", f_G[11]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_e", f_G[12]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_mu", f_G[13]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_e_nu_tau", f_G[14]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_mu_anti_nu_mu", f_G[15]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_mu_anti_nu_tau", f_G[16]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_mu_nu_mu", f_G[17]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_mu_nu_tau", f_G[18]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_nu_tau_anti_nu_tau", f_G[19]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_nu_tau_nu_tau", f_G[20]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_e", f_G[21]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_mu", f_G[22]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_e_anti_tau", f_G[23]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_e", f_G[24]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_mu", f_G[25]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_e_tau", f_G[26]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_mu_anti_mu", f_G[27]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_mu_anti_tau", f_G[28]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_mu_mu", f_G[29]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_mu_tau", f_G[30]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_tau_anti_tau", f_G[31]},
    {"sumSqAmpl_chi_dm_1_anti_chi_dm_1_to_anti_tau_tau", f_G[32]},
    {"width_h", f_G[33]},
    {"width_W", f_G[34]},
    {"width_Z", f_G[35]},
    {"width_t", f_G[36]},
};


} // End of namespace u1f2to2
