FROM registry.fedoraproject.org/fedora:36

ARG username=vscode

RUN dnf update -y && \
    dnf upgrade -y && \
    dnf install \
                gcc \
                gfortran \
                g++ \
                gsl \
                gsl-devel \
                texlive \
                ImageMagick \
                dvipng \
                coreutils \
                qtchooser \
                cmake \
                git \
                ninja-build \
                eigen3-devel \
                tbb \
                tbb-devel \
                wget \
                doxygen \
                git-clang-format \
                -y && \ 
    dnf clean all  

RUN useradd ${username}

# Installing MARTY
USER ${username}

WORKDIR /home/${username}

RUN git clone https://github.com/docbrown1955/marty-public.git && \
    cd marty-public && \
    git checkout master && \
    mkdir bin include lib build 

RUN cd /home/${username}/marty-public/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=.install -G Ninja && \
    cmake --build . && \
    cmake --install .

ENV INSTALLMARTYPATH="/home/${username}/marty-public/build/.install"
ENV PATH=$INSTALLMARTYPATH/bin:$PATH
ENV LD_LIBRARY_PATH=$INSTALLMARTYPATH/lib
ENV LIBRARY_PATH=$INSTALLMARTYPATH/lib
ENV C_INCLUDE_PATH=$INSTALLMARTYPATH/include
ENV CPATH=$INSTALLMARTYPATH/include

USER ${username}

CMD ["sleep", "infinity"]
