# Contains gcc-13
FROM mcr.microsoft.com/devcontainers/cpp:ubuntu24.04

ARG username=vscode

# Installing packages for MARTY's dependencies
RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y install --no-install-recommends \
        coreutils \
        build-essential \
        gcc \
        g++ \
        gfortran \
        libgsl-dev \
        libgslcblas0 \
        qtbase5-dev \
        qtchooser \
        qt5-qmake \
        qtbase5-dev-tools \
        dvipng \
        lcov \
        cmake \
        texlive \
        texlive-latex-extra \
        texlive-luatex \
        imagemagick \
        ninja-build \
        git \
        clang-format && \
    apt-get clean

RUN apt-get install -y ca-certificates && \
    update-ca-certificates

# Changing user to vscode
USER ${username}

WORKDIR /home/${username}

RUN git clone https://github.com/docbrown1955/marty-public.git && \
    cd marty-public && \
    git checkout dac95a471e0c7ea12f18ba13df0a7383406fdd16 && \
    mkdir bin include lib build

ENV CC=gcc
ENV CXX=g++
ENV FC=gfortran

RUN cd /home/${username}/marty-public/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=.install -G Ninja && \
    cmake --build . && \
    cmake --install .

ENV INSTALLMARTYPATH="/home/${username}/marty-public/build/.install"
ENV PATH=$INSTALLMARTYPATH/bin:$PATH
ENV LD_LIBRARY_PATH=$INSTALLMARTYPATH/lib
ENV LIBRARY_PATH=$INSTALLMARTYPATH/lib
ENV C_INCLUDE_PATH=$INSTALLMARTYPATH/include
ENV CPATH=$INSTALLMARTYPATH/include

CMD ["sleep", "infinity"]
