# Fedora 41 uses gcc-14, so we specify gcc-13 explicitly
FROM registry.fedoraproject.org/fedora:41

ARG username=vscode

RUN dnf update -y && \
    dnf upgrade -y && \
    dnf install \
        gcc-13 \
        gfortran-13 \
        g++-13 \
        gsl \
        gsl-devel \
        texlive \
        ImageMagick \
        dvipng \
        coreutils \
        qtchooser \
        cmake \
        git \
        ninja-build \
        git-clang-format \
        -y && \
    dnf clean all  

RUN useradd ${username}

USER ${username}

WORKDIR /home/${username}

# Installing MARTY
RUN git clone https://github.com/docbrown1955/marty-public.git && \
    cd marty-public && \
    git checkout separating_global && \
    mkdir bin include lib build 

ENV CC=/usr/bin/gcc-13
ENV CXX=/usr/bin/g++-13
ENV FC=/usr/bin/gfortran-13

RUN cd /home/${username}/marty-public/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=.install -G Ninja && \
    cmake --build . && \
    cmake --install .

ENV INSTALLMARTYPATH="/home/${username}/marty-public/build/.install"
ENV PATH=$INSTALLMARTYPATH/bin:$PATH
ENV LD_LIBRARY_PATH=$INSTALLMARTYPATH/lib
ENV LIBRARY_PATH=$INSTALLMARTYPATH/lib
ENV C_INCLUDE_PATH=$INSTALLMARTYPATH/include
ENV CPATH=$INSTALLMARTYPATH/include

# Explicitly adding the path of -lgfortran 13 to the library path
ENV LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/13:$LD_LIBRARY_PATH
ENV LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/13:$LIBRARY_PATH

CMD ["sleep", "infinity"]
