FROM registry.fedoraproject.org/fedora:41

ARG username=vscode

# Installing common dependencies
RUN dnf update -y && \
    dnf upgrade -y && \
    dnf install \
                gcc \
                gfortran \
                g++ \
                gsl \
                gsl-devel \
                texlive \
                ImageMagick \
                dvipng \
                coreutils \
                qtchooser \
                cmake \
                git \
                ninja-build \
                git-clang-format \
                -y && \ 
    dnf clean all  

RUN useradd ${username}

# Installing MARTY
USER ${username}

WORKDIR /home/${username}

RUN git clone https://github.com/docbrown1955/marty-public.git && \
    cd marty-public && \
    git checkout dac95a471e0c7ea12f18ba13df0a7383406fdd16 && \
    mkdir bin include lib build 

RUN cd /home/${username}/marty-public/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=.install -G Ninja && \
    cmake --build . && \
    cmake --install .

ENV INSTALLMARTYPATH="/home/${username}/marty-public/build/.install"
ENV PATH=$INSTALLMARTYPATH/bin:$PATH
ENV LD_LIBRARY_PATH=$INSTALLMARTYPATH/lib
ENV LIBRARY_PATH=$INSTALLMARTYPATH/lib
ENV C_INCLUDE_PATH=$INSTALLMARTYPATH/include
ENV CPATH=$INSTALLMARTYPATH/include

#Installing CMA-ES dependencies
USER root   
RUN dnf install \                 
        eigen3-devel \
        tbb \
        tbb-devel \
        wget \
        doxygen -y && \ 
    dnf clean all 

USER ${username}

CMD ["sleep", "infinity"]
