name: Test darkpack

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ['fedora36', 'debian']
    
    steps:
    - name: Cloning the last commit
      uses: actions/checkout@v2

    - name: List files in the workspace
      run: ls -la ${GITHUB_WORKSPACE}

    - name: Set permissions on workspace
      run: |
        sudo chown -R $(id -u):$(id -g) ${GITHUB_WORKSPACE}
        chmod -R 755 ${GITHUB_WORKSPACE}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Pull the docker images
      run: docker pull docker.io/marcopalmiotto/darkpack-deploy:${{ matrix.distro }}

    - name: Run tests in ${{ matrix.distro }} container
      run: |
        docker run --rm \
          --user $(id -u):$(id -g) \
          --mount type=bind,src=${GITHUB_WORKSPACE},target=/home/darkpack \
          -w /home/darkpack \
          docker.io/marcopalmiotto/darkpack-deploy:${{ matrix.distro }} \
          /bin/bash -c "./run_CI.sh"
