name: Test darkpack

on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ['fedora36', 'debian']
    
    steps:
    - name: Cloning the last commit
      uses: actions/checkout@v2

    - name: List files in the workspace
      run: ls ${GITHUB_WORKSPACE}

    - name: Create build directory
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/build
        chmod -R 777 ${GITHUB_WORKSPACE}/build
    

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Pull the docker images
      run: docker pull docker.io/marcopalmiotto/darkpack-deploy:${{ matrix.distro }}

    - name: Run tests in ${{ matrix.distro }} container
      run: docker run -v "${GITHUB_WORKSPACE}:/darkpack:rw" -w /darkpack docker.io/marcopalmiotto/darkpack-deploy:${{ matrix.distro }} /bin/bash -c "mkdir -p build && sudo chmod -R 777 build && ./run_CI.sh"
           
